version: "3"

services: 
  imply:
    image: anhngd/imply:${IMPLY_VERSION}
    container_name: imply-pivot
    build: .
    ports:
      - 9095:9095
    entrypoint: imply/bin/supervise -c imply/conf/supervise/pivot.conf
    volumes:
      - ./conf:/imply/conf

  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  mysql_data: {}